"""Install / uninstall polylogue background service per platform."""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

from .platform_detect import data_dir, detect_platform
from .service_config import service_host, service_port


def _python_executable() -> str:
    return sys.executable


def _module_cmd() -> list[str]:
    return [_python_executable(), "-m", "deepiri_polylogue.service_daemon"]


def install_hook() -> dict[str, str]:
    """Write shell env snippet (all platforms)."""
    config_dir = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "polylogue"
    config_dir.mkdir(parents=True, exist_ok=True)
    env_file = config_dir / "service.env"
    env_file.write_text(
        "\n".join(
            [
                "# Auto-generated by deepiri-polylogue service install",
                f'export POLYLOGUE_SERVICE_HOST="{service_host()}"',
                f'export POLYLOGUE_SERVICE_PORT="{service_port()}"',
                f'export POLYLOGUE_DATA_DIR="{data_dir()}"',
                "",
            ]
        ),
        encoding="utf-8",
    )
    return {"env_file": str(env_file), "platform": detect_platform()}


def install_systemd_user() -> str:
    unit_dir = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "systemd" / "user"
    unit_dir.mkdir(parents=True, exist_ok=True)
    unit_file = unit_dir / "deepiri-polylogue.service"
    exec_start = " ".join(_module_cmd())
    unit_file.write_text(
        "\n".join(
            [
                "[Unit]",
                "Description=Deepiri Polylogue coordination service",
                "After=network.target",
                "",
                "[Service]",
                "Type=simple",
                f"ExecStart={exec_start}",
                "Restart=on-failure",
                "RestartSec=5",
                f"Environment=POLYLOGUE_SERVICE_HOST={service_host()}",
                f"Environment=POLYLOGUE_SERVICE_PORT={service_port()}",
                "",
                "[Install]",
                "WantedBy=default.target",
                "",
            ]
        ),
        encoding="utf-8",
    )
    subprocess.run(["systemctl", "--user", "daemon-reload"], check=False)
    subprocess.run(["systemctl", "--user", "enable", "deepiri-polylogue.service"], check=False)
    subprocess.run(["systemctl", "--user", "start", "deepiri-polylogue.service"], check=False)
    return str(unit_file)


def install_launchd() -> str:
    plist_dir = Path.home() / "Library" / "LaunchAgents"
    plist_dir.mkdir(parents=True, exist_ok=True)
    plist = plist_dir / "com.deepiri.polylogue.plist"
    py = _python_executable()
    plist.write_text(
        f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.deepiri.polylogue</string>
  <key>ProgramArguments</key>
  <array>
    <string>{py}</string>
    <string>-m</string><string>deepiri_polylogue.service_daemon</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>EnvironmentVariables</key>
  <dict>
    <key>POLYLOGUE_SERVICE_HOST</key><string>{service_host()}</string>
    <key>POLYLOGUE_SERVICE_PORT</key><string>{service_port()}</string>
  </dict>
</dict>
</plist>
""",
        encoding="utf-8",
    )
    subprocess.run(["launchctl", "unload", str(plist)], check=False, capture_output=True)
    subprocess.run(["launchctl", "load", str(plist)], check=False)
    return str(plist)


def install_windows_task() -> str:
    script_dir = Path(data_dir()) / "bin"
    script_dir.mkdir(parents=True, exist_ok=True)
    bat = script_dir / "start-polylogue-service.bat"
    bat.write_text(
        "\n".join(
            [
                "@echo off",
                f'"{_python_executable()}" -m deepiri_polylogue.service_daemon',
                "",
            ]
        ),
        encoding="utf-8",
    )
    task_name = "DeepiriPolylogue"
    subprocess.run(
        [
            "schtasks",
            "/Create",
            "/TN",
            task_name,
            "/TR",
            str(bat),
            "/SC",
            "ONLOGON",
            "/RL",
            "LIMITED",
            "/F",
        ],
        check=False,
        capture_output=True,
    )
    return str(bat)


def install_service() -> dict[str, str]:
    hook = install_hook()
    plat = detect_platform()
    artifact = ""
    if plat in ("linux", "wsl"):
        if shutil.which("systemctl"):
            artifact = install_systemd_user()
        else:
            artifact = "no-systemd: run `deepiri-polylogue service start --foreground` manually"
    elif plat == "macos":
        artifact = install_launchd()
    elif plat == "windows":
        artifact = install_windows_task()
    else:
        artifact = "manual: deepiri-polylogue service start --foreground"
    return {**hook, "platform": plat, "service_unit": artifact}


def uninstall_service() -> None:
    plat = detect_platform()
    if plat in ("linux", "wsl"):
        subprocess.run(["systemctl", "--user", "disable", "deepiri-polylogue.service"], check=False)
        subprocess.run(["systemctl", "--user", "stop", "deepiri-polylogue.service"], check=False)
        unit = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "systemd" / "user" / "deepiri-polylogue.service"
        unit.unlink(missing_ok=True)
        subprocess.run(["systemctl", "--user", "daemon-reload"], check=False)
    elif plat == "macos":
        plist = Path.home() / "Library" / "LaunchAgents" / "com.deepiri.polylogue.plist"
        subprocess.run(["launchctl", "unload", str(plist)], check=False, capture_output=True)
        plist.unlink(missing_ok=True)
    elif plat == "windows":
        subprocess.run(["schtasks", "/Delete", "/TN", "DeepiriPolylogue", "/F"], check=False, capture_output=True)
